version: '3.8'

services:
  flask_service:
    image: sanajabbar88/gasdet-flask_service:latest
    command: ["python", "flask_app.py"]  # Replace with the actual entry command for your Flask app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongodb
    networks:
      - app-network
    devices:
      - "/dev/video0:/dev/video0"
    user: "1000:1000"
    privileged: true

  streamlit_service:
    image: sanajabbar88/gasdet-streamlit_service:latest
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.headless=true"]
    ports:
      - "8501:8501"
    depends_on:
      - flask_service
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
