version: '3.8'

services:
  flask_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "flask_app.py"]
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - CAMERA_IP_URL=http://<ip_address>:<port>/path  # Set the IP camera URL here
    depends_on:
      - mongodb  # Ensure MongoDB starts first
    networks:
      - app-network
    user: "1000:1000"
    privileged: true  # Only if other privileged operations are required

  streamlit_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.headless=true"]
    ports:
      - "8501:8501"
    depends_on:
      - flask_service
    networks:
      - app-network
    environment:
      - CAMERA_IP_URL=http://<ip_address>:<port>/path  # Set the IP camera URL here

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
