version: '3.8'

services:
  flask_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "flask_app.py"]
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongodb  # Ensure MongoDB starts first
    networks:
      - app-network
    devices:
      - "/dev/video0:/dev/video0"  # Share the host's /dev/video0 with the container
    user: "1000:1000"
    privileged: true  # Gives the container extended permissions to access devices

  streamlit_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.headless=true"]
    ports:
      - "8501:8501"
    depends_on:
      - flask_service
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

