version: '3.8'

services:
  flask_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "flask_app.py"]
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  streamlit_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.headless=true"]
    ports:
      - "8501:8501"
    depends_on:
      - flask_service
