version: '3.8'

services:
  flask_service:
    image: sanajabbar88/gasdet-flask_service:latest
    command: ["python", "/app/flask_app.py", "--host=0.0.0.0", "--port=5000"]  # Replace with the actual entry command for your Flask app
    ports:
      - "5000:5000"
    environment:
       - FLASK_ENV=development
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - .:/app  # Syncs all files from the current directory to /app in the container

  streamlit_service:
    image: sanajabbar88/gasdet-streamlit_service:latest
    command: ["streamlit", "run", "/app/streamlit_app.py", "--server.port=8501", "--server.headless=true"]
    ports:
      - "8501:8501"
    depends_on:
      - flask_service
    networks:
      - app-network
    volumes:
      - .:/app  # optional, for local development

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
